# PostgreSQL database configuration

connection: &connection
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres
  timeout: 5000

development:
  <<: *connection
  database: rails_development

test:
  <<: *connection
  database: rails_test

production:
  <<: *connection
  database: rails_production
